server:
  port: 9000
spring:
  application:
    name: spring-cloud-eureka-demo
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否将eureka自身作为应用注册到eureka注册中心
#    fetch-registry表示是否从Eureka Server获取注册信息，默认为true。因为本例是一个单点的Eureka Server，不需要同步其他Eureka Server节点数据，所以设置为false
    fetch-registry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/