server:
  port: 9003

spring:
  application:
    name: spring-cloud-service-demo

eureka:
  instance:
    prefer-ip-address: true #表示将自己的ip注册到Eureka Server上，如果是false的话会显示hostname而不是ip地址。
#    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
