server:
  port: 9001
spring:
  application:
    name: spring-cloud-config-server-demo
  rabbitmq:
    host: localhost
    virtual-host: spring-cloud-bus
    username: admin
    password: admin
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xia45399/spring-cloud-demos
          search-paths: config
          username:
          password:
#        native:
#          search-locations:
#  profiles:
#    active: native
management:
  endpoints:
    web:
      exposure:
        include: actuator


