server:
  port: 9001
spring:
  application:
    name: spring-cloud-config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xia45399/spring-cloud-demos
          search-paths: config
          username:
          password:
#        native:
#          search-locations:
#  profiles:
#    active: native



